# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/adminstrator/Documents/SCHOOL YEAR 2022-2023/Fall 2022/CO456/Final Project/AntichessAI"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/adminstrator/Documents/SCHOOL YEAR 2022-2023/Fall 2022/CO456/Final Project/AntichessAI"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/adminstrator/Documents/SCHOOL YEAR 2022-2023/Fall 2022/CO456/Final Project/AntichessAI/CMakeFiles" "/Users/adminstrator/Documents/SCHOOL YEAR 2022-2023/Fall 2022/CO456/Final Project/AntichessAI//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/adminstrator/Documents/SCHOOL YEAR 2022-2023/Fall 2022/CO456/Final Project/AntichessAI/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AntichessAI

# Build rule for target.
AntichessAI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AntichessAI
.PHONY : AntichessAI

# fast build rule for target.
AntichessAI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/build
.PHONY : AntichessAI/fast

src/cpp-chess/chess.o: src/cpp-chess/chess.cpp.o
.PHONY : src/cpp-chess/chess.o

# target to build an object file
src/cpp-chess/chess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/cpp-chess/chess.cpp.o
.PHONY : src/cpp-chess/chess.cpp.o

src/cpp-chess/chess.i: src/cpp-chess/chess.cpp.i
.PHONY : src/cpp-chess/chess.i

# target to preprocess a source file
src/cpp-chess/chess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/cpp-chess/chess.cpp.i
.PHONY : src/cpp-chess/chess.cpp.i

src/cpp-chess/chess.s: src/cpp-chess/chess.cpp.s
.PHONY : src/cpp-chess/chess.s

# target to generate assembly for a file
src/cpp-chess/chess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/cpp-chess/chess.cpp.s
.PHONY : src/cpp-chess/chess.cpp.s

src/evaluate/evaluate.o: src/evaluate/evaluate.cpp.o
.PHONY : src/evaluate/evaluate.o

# target to build an object file
src/evaluate/evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/evaluate/evaluate.cpp.o
.PHONY : src/evaluate/evaluate.cpp.o

src/evaluate/evaluate.i: src/evaluate/evaluate.cpp.i
.PHONY : src/evaluate/evaluate.i

# target to preprocess a source file
src/evaluate/evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/evaluate/evaluate.cpp.i
.PHONY : src/evaluate/evaluate.cpp.i

src/evaluate/evaluate.s: src/evaluate/evaluate.cpp.s
.PHONY : src/evaluate/evaluate.s

# target to generate assembly for a file
src/evaluate/evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/evaluate/evaluate.cpp.s
.PHONY : src/evaluate/evaluate.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/search/search.o: src/search/search.cpp.o
.PHONY : src/search/search.o

# target to build an object file
src/search/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/search/search.cpp.o
.PHONY : src/search/search.cpp.o

src/search/search.i: src/search/search.cpp.i
.PHONY : src/search/search.i

# target to preprocess a source file
src/search/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/search/search.cpp.i
.PHONY : src/search/search.cpp.i

src/search/search.s: src/search/search.cpp.s
.PHONY : src/search/search.s

# target to generate assembly for a file
src/search/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AntichessAI.dir/build.make CMakeFiles/AntichessAI.dir/src/search/search.cpp.s
.PHONY : src/search/search.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AntichessAI"
	@echo "... src/cpp-chess/chess.o"
	@echo "... src/cpp-chess/chess.i"
	@echo "... src/cpp-chess/chess.s"
	@echo "... src/evaluate/evaluate.o"
	@echo "... src/evaluate/evaluate.i"
	@echo "... src/evaluate/evaluate.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/search/search.o"
	@echo "... src/search/search.i"
	@echo "... src/search/search.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

